// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  boxId: __t.u64(),
  kind: __t.string(),
  what: __t.string(),
  model: __t.string(),
  units: __t.u64(),
  unitKind: __t.string(),
  costMicro: __t.u64(),
  priceMicro: __t.u64(),
  ref: __t.string(),
  prevHash: __t.string(),
  hash: __t.string(),
  sharedPrevHash: __t.option(__t.string()),
  sharedHash: __t.option(__t.string()),
};
