// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  boxId: __t.u64().primaryKey().name("box_id"),
  dialectText: __t.string().name("dialect_text"),
  themeId: __t.string().name("theme_id"),
  styleJson: __t.string().name("style_json"),
  updatedAt: __t.timestamp().name("updated_at"),
});
