// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  boxId: __t.u64().name("box_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  opsJson: __t.string().name("ops_json"),
  inverseJson: __t.string().name("inverse_json"),
  summary: __t.string(),
  source: __t.string(),
  state: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  flippedAt: __t.timestamp().name("flipped_at"),
});
