// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  boxId: __t.u64().name("box_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  kind: __t.string(),
  what: __t.string(),
  model: __t.string(),
  units: __t.u64(),
  unitKind: __t.string().name("unit_kind"),
  costMicro: __t.u64().name("cost_micro"),
  priceMicro: __t.u64().name("price_micro"),
  ref: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  prevHash: __t.string().name("prev_hash"),
  hash: __t.string(),
  sharedPrevHash: __t.option(__t.string()).name("shared_prev_hash"),
  sharedHash: __t.option(__t.string()).name("shared_hash"),
});
