// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  boxId: __t.u64().name("box_id"),
  text: __t.string(),
  type: __t.string(),
  note: __t.string(),
  caseSensitive: __t.bool().name("case_sensitive"),
  createdAt: __t.timestamp().name("created_at"),
});
