// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  boxId: __t.u64().name("box_id"),
  kind: __t.string(),
  text: __t.string(),
  chipsJson: __t.string().name("chips_json"),
  component: __t.string(),
  reveal: __t.string(),
  blocksJson: __t.string().name("blocks_json"),
  createdAt: __t.timestamp().name("created_at"),
});
