// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Box = __t.object("Box", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Box = __Infer<typeof Box>;

export const BoxUi = __t.object("BoxUi", {
  boxId: __t.u64(),
  dialectText: __t.string(),
  themeId: __t.string(),
  styleJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type BoxUi = __Infer<typeof BoxUi>;

export const Card = __t.object("Card", {
  id: __t.string(),
  title: __t.string(),
  kind: __t.string(),
  href: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  w: __t.f64(),
  h: __t.f64(),
  thicknessMm: __t.f64(),
  rotation: __t.f64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Card = __Infer<typeof Card>;

export const EditBatch = __t.object("EditBatch", {
  id: __t.string(),
  boxId: __t.u64(),
  ownerIdentity: __t.identity(),
  opsJson: __t.string(),
  inverseJson: __t.string(),
  summary: __t.string(),
  source: __t.string(),
  state: __t.string(),
  createdAt: __t.timestamp(),
  flippedAt: __t.timestamp(),
});
export type EditBatch = __Infer<typeof EditBatch>;

export const Entry = __t.object("Entry", {
  id: __t.u64(),
  boxId: __t.u64(),
  ownerIdentity: __t.identity(),
  kind: __t.string(),
  what: __t.string(),
  model: __t.string(),
  units: __t.u64(),
  unitKind: __t.string(),
  costMicro: __t.u64(),
  priceMicro: __t.u64(),
  ref: __t.string(),
  createdAt: __t.timestamp(),
  prevHash: __t.string(),
  hash: __t.string(),
  sharedPrevHash: __t.option(__t.string()),
  sharedHash: __t.option(__t.string()),
});
export type Entry = __Infer<typeof Entry>;

export const GlossaryTerm = __t.object("GlossaryTerm", {
  id: __t.string(),
  boxId: __t.u64(),
  text: __t.string(),
  type: __t.string(),
  note: __t.string(),
  caseSensitive: __t.bool(),
  createdAt: __t.timestamp(),
});
export type GlossaryTerm = __Infer<typeof GlossaryTerm>;

export const Line = __t.object("Line", {
  id: __t.u64(),
  boxId: __t.u64(),
  kind: __t.string(),
  text: __t.string(),
  chipsJson: __t.string(),
  component: __t.string(),
  reveal: __t.string(),
  blocksJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type Line = __Infer<typeof Line>;

export const NavItem = __t.object("NavItem", {
  id: __t.string(),
  boxId: __t.u64(),
  parentId: __t.string(),
  label: __t.string(),
  icon: __t.string(),
  targetJson: __t.string(),
  order: __t.f64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NavItem = __Infer<typeof NavItem>;

export const Owner = __t.object("Owner", {
  identity: __t.identity(),
  onChain: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Owner = __Infer<typeof Owner>;

export const Page = __t.object("Page", {
  id: __t.string(),
  boxId: __t.u64(),
  title: __t.string(),
  blocksJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Page = __Infer<typeof Page>;

export const Presence = __t.object("Presence", {
  identity: __t.identity(),
  boxId: __t.u64(),
  lastSeen: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const RouteRule = __t.object("RouteRule", {
  id: __t.u64(),
  intent: __t.string(),
  model: __t.string(),
  permission: __t.string(),
  marginBp: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type RouteRule = __Infer<typeof RouteRule>;

export const Session = __t.object("Session", {
  id: __t.u64(),
  boxId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const Theme = __t.object("Theme", {
  id: __t.string(),
  name: __t.string(),
  scheme: __t.string(),
  specText: __t.string(),
  tokensJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Theme = __Infer<typeof Theme>;

