// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  title: __t.string(),
  kind: __t.string(),
  href: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  w: __t.f64(),
  h: __t.f64(),
  thicknessMm: __t.f64(),
  rotation: __t.f64(),
};
