// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendEntryReducer from "../append_entry_reducer";
import AppendLineReducer from "../append_line_reducer";
import CreateBoxReducer from "../create_box_reducer";
import MoveCardReducer from "../move_card_reducer";
import OpenSessionReducer from "../open_session_reducer";
import RecordEditBatchReducer from "../record_edit_batch_reducer";
import RemoveGlossaryTermReducer from "../remove_glossary_term_reducer";
import RemoveNavItemReducer from "../remove_nav_item_reducer";
import RemovePageReducer from "../remove_page_reducer";
import SetBoxUiReducer from "../set_box_ui_reducer";
import SetEditStateReducer from "../set_edit_state_reducer";
import SetOnChainReducer from "../set_on_chain_reducer";
import TouchPresenceReducer from "../touch_presence_reducer";
import UpsertCardReducer from "../upsert_card_reducer";
import UpsertGlossaryTermReducer from "../upsert_glossary_term_reducer";
import UpsertNavItemReducer from "../upsert_nav_item_reducer";
import UpsertPageReducer from "../upsert_page_reducer";
import UpsertRouteRuleReducer from "../upsert_route_rule_reducer";
import UpsertThemeReducer from "../upsert_theme_reducer";

export type AppendEntryParams = __Infer<typeof AppendEntryReducer>;
export type AppendLineParams = __Infer<typeof AppendLineReducer>;
export type CreateBoxParams = __Infer<typeof CreateBoxReducer>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type OpenSessionParams = __Infer<typeof OpenSessionReducer>;
export type RecordEditBatchParams = __Infer<typeof RecordEditBatchReducer>;
export type RemoveGlossaryTermParams = __Infer<typeof RemoveGlossaryTermReducer>;
export type RemoveNavItemParams = __Infer<typeof RemoveNavItemReducer>;
export type RemovePageParams = __Infer<typeof RemovePageReducer>;
export type SetBoxUiParams = __Infer<typeof SetBoxUiReducer>;
export type SetEditStateParams = __Infer<typeof SetEditStateReducer>;
export type SetOnChainParams = __Infer<typeof SetOnChainReducer>;
export type TouchPresenceParams = __Infer<typeof TouchPresenceReducer>;
export type UpsertCardParams = __Infer<typeof UpsertCardReducer>;
export type UpsertGlossaryTermParams = __Infer<typeof UpsertGlossaryTermReducer>;
export type UpsertNavItemParams = __Infer<typeof UpsertNavItemReducer>;
export type UpsertPageParams = __Infer<typeof UpsertPageReducer>;
export type UpsertRouteRuleParams = __Infer<typeof UpsertRouteRuleReducer>;
export type UpsertThemeParams = __Infer<typeof UpsertThemeReducer>;

